import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import { AuthGuard } from '@/components/auth/auth-guard'
import { AppLayoutClient } from '@/components/ui/app-layout-client'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: 'var(--sidebar)' }}
      >
        <AppLayoutClient>
          <AuthGuard>
            {children}
          </AuthGuard>
          <Toaster position="bottom-left" />
        </AppLayoutClient>
      </body>
    </html>
  );
}
